"""add name column to test_models

Revision ID: b2b3948a8669
Revises: 7d92a550c90d
Create Date: 2026-02-12 01:52:45.982967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b3948a8669'
down_revision: Union[str, Sequence[str], None] = '7d92a550c90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_models', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_models', 'name')
    # ### end Alembic commands ###
