"""add base model fields

Revision ID: da07f189f548
Revises: b2b3948a8669
Create Date: 2026-02-12 13:02:58.322675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da07f189f548'
down_revision: Union[str, Sequence[str], None] = 'b2b3948a8669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_models_id'), table_name='test_models')
    op.drop_table('test_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_models_pkey'))
    )
    op.create_index(op.f('ix_test_models_id'), 'test_models', ['id'], unique=False)
    # ### end Alembic commands ###
